<a href="https://colab.research.google.com/github/Francisroyce/Francisroyce/blob/main/Tensorflow_and_projects_on_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
print('hellow world')

hellow world


# Checking tensor dimension and shapes

In [37]:
import tensorflow as tf


In [38]:
# check for 0-D(dimension), to check the shapes
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [39]:
# checking for 1-D(dimension), to check the shapes
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [40]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [41]:
# checking for a float
tensor_one_d = tf.constant([2, 0, -3, 8, 90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [42]:
# checking on 2-D(dimension) tensor, to check the shape
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
    ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [43]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],

    [[10, 2, 0],
     [1, 0, 2]],

    [[5, 8, 0],
     [2, 7, 0]],

    [[2, 1, 9],
     [4, -3, 32]]
])

print(tensor_three_d)


tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [44]:
tensor_three_d.shape, tensor_two_d.shape, tensor_one_d.shape

(TensorShape([4, 2, 3]), TensorShape([4, 3]), TensorShape([5]))

In [45]:
# checking for 4-D tensors
import tensorflow as tf

tensor_four_d = tf.constant([
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ],
    [
        [
            [13, 14, 15],
            [16, 17, 18]
        ],
        [
            [19, 20, 21],
            [22, 23, 24]
        ]
    ]
])

print(tensor_four_d)



tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


# Cast method

In [46]:
tensor_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
print(tensor_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [47]:
tensor_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
casted_tensor_d = tf.cast(tensor_d, dtype=tf.int32)
print(tensor_d)
print(casted_tensor_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [48]:
tensor_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
casted_tensor_d = tf.cast(tensor_d, dtype=tf.bool)
print(tensor_d)
print(casted_tensor_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [49]:
# checking for bool
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [50]:
# checking for tensor strings
tensor_s = tf.constant(['hello world'])
print(tensor_s)

tf.Tensor([b'hello world'], shape=(1,), dtype=string)


In [51]:
# checking for tensor strings
tensor_s = tf.constant(['hello world', 'hi'])
print(tensor_s)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


# Converting a numpy array into a tensor

In [52]:
import numpy as np


In [53]:
np_array = np.array([1, 2, 3])
print(np_array)

[1 2 3]


In [54]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [55]:
# construct identity matrix or batch of matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype = tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [56]:
# construct identity matrix or batch of matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype = tf.dtypes.float32,
    name=None
)
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [57]:
# setting batch shape
# construct identity matrix or batch of matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[3,],
    dtype = tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [58]:
# construct identity matrix or batch of matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2, 4],
    dtype = tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 4, 3, 3), dtype=float32)


# Fill method

In [59]:
fill_tennsor = tf.fill([1, 3, 4], 5, name=None)
print(fill_tennsor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


# Ones method

In [60]:
# create a tensor with all elements set to one(1)
ones_tensor = tf.ones([5, 3],
                       dtype=tf.dtypes.float32,
                       name=None)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [61]:
# create a tensor with all elements set to one(1)
ones_tensor = tf.ones([5, 3, 2],
                       dtype=tf.dtypes.float32,
                       name=None)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


#Ones_like method

In [62]:
# create a tensor of all one that has the same shape as the input
ones_like_tensor = tf.ones_like(fill_tennsor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


# Zeros method

In [63]:
# creates a tensor with all eleements set to zero
zero_tensor = tf.zeros([5, 3],
                       dtype=tf.dtypes.float32,
                       name=None)
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


# Shape method

In [64]:
shape_tensors =tf.shape([3, 5],
                        out_type=tf.dtypes.int32,
                        name=None)
print(shape_tensors)

tf.Tensor([2], shape=(1,), dtype=int32)


# Rank Method

In [65]:
# returns the rank of a tensor
rank_teensor = tf.rank(([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]))
print(rank_teensor)

tf.Tensor(2, shape=(), dtype=int32)


In [66]:
# returns the rank of a tensor
rank_tensor = tf.constant(([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]))
tf.rank(rank_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Size method

In [67]:

# returns tyhe size of a tensor
tf.size(rank_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

# Random.Normal Tensors

In [68]:
random_tensors =tf.random.normal(
    [3, 2],
    mean = 0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensors)

tf.Tensor(
[[ 0.8044463   0.71110183]
 [ 0.05674146  1.300224  ]
 [-1.3827544   0.13503087]], shape=(3, 2), dtype=float32)


In [69]:
# let's modify the mean
random_tensors =tf.random.normal(
    [3, 2],
    mean = 100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensors)

tf.Tensor(
[[100.09812  100.321465]
 [ 99.72952  100.82132 ]
 [100.6081    98.98467 ]], shape=(3, 2), dtype=float32)


# Random.Uniform distribution

In [70]:
random_uniform_tensors = tf.random.uniform(
    [1,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform_tensors)


tf.Tensor([0.5539329], shape=(1,), dtype=float32)


# Seed

In [71]:
# a reproducible sequence of event
tf.random.set_seed(5)

In [72]:
import tensorflow as tf
import numpy as np

# Set the random seed for TensorFlow
tf.random.set_seed(5)

# Generate a random matrix
random_matrix = tf.random.normal((3, 3), mean=0, stddev=1)

# Convert the TensorFlow tensor to a NumPy array for easy display
numpy_matrix = random_matrix.numpy()

# Print the random matrix
print("Random Matrix:")
print(numpy_matrix)


Random Matrix:
[[-0.18030666 -0.95028627 -0.03964049]
 [-0.7425406   1.3231523  -0.61854804]
 [ 0.85406643 -0.08899953  2.4488697 ]]


In [73]:
import tensorflow as tf
import numpy as np

# Set the random seed for TensorFlow
tf.random.set_seed(5)

# Generate a random matrix
random_matrix = tf.random.normal((3, 3), mean=0, stddev=1)

# Convert the TensorFlow tensor to a NumPy array for easy display
numpy_matrix = random_matrix.numpy()

# Print the random matrix
print("Random Matrix:")
print(numpy_matrix)


Random Matrix:
[[-0.18030666 -0.95028627 -0.03964049]
 [-0.7425406   1.3231523  -0.61854804]
 [ 0.85406643 -0.08899953  2.4488697 ]]


running the above codes, we can see it is reproducible

In [74]:
# modifying the above can give us something different
import tensorflow as tf
import numpy as np

# Set the random seed for TensorFlow
tf.random.set_seed(4)

# Generate a random matrix
random_matrix = tf.random.normal((3, 3), mean=0, stddev=1)

# Convert the TensorFlow tensor to a NumPy array for easy display
numpy_matrix = random_matrix.numpy()

# Print the random matrix
print("Random Matrix:")
print(numpy_matrix)


Random Matrix:
[[-0.07676513 -0.2082602   1.9333363 ]
 [ 1.175166    1.4444145   1.3351023 ]
 [ 0.0987538   0.47003895 -0.8959344 ]]


TENSORS AND VARIABLES

Basic initialization and casting
indexing

Tensor indexing

In [75]:
tensor_indexed = tf.constant([3, 6, 2, 4, 6, 66, 7])
print(tensor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [76]:
print(tensor_indexed[0])

tf.Tensor(3, shape=(), dtype=int32)


In [79]:
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])
print(tensor_indexed[1:6])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
