<a href="https://colab.research.google.com/github/Francisroyce/Francisroyce/blob/main/Tensorflow_and_projects_on_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
print('hellow world')

hellow world


# Checking tensor dimension and shapes

In [28]:
import tensorflow as tf


In [29]:
# check for 0-D(dimension), to check the shapes
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [30]:
# checking for 1-D(dimension), to check the shapes
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [31]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [32]:
# checking for a float
tensor_one_d = tf.constant([2, 0, -3, 8, 90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [33]:
# checking on 2-D(dimension) tensor, to check the shape
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
    ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [34]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],

    [[10, 2, 0],
     [1, 0, 2]],

    [[5, 8, 0],
     [2, 7, 0]],

    [[2, 1, 9],
     [4, -3, 32]]
])

print(tensor_three_d)


tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [35]:
tensor_three_d.shape, tensor_two_d.shape, tensor_one_d.shape

(TensorShape([4, 2, 3]), TensorShape([4, 3]), TensorShape([5]))

In [36]:
# checking for 4-D tensors
import tensorflow as tf

tensor_four_d = tf.constant([
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ],
    [
        [
            [13, 14, 15],
            [16, 17, 18]
        ],
        [
            [19, 20, 21],
            [22, 23, 24]
        ]
    ]
])

print(tensor_four_d)



tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


# Cast method

In [37]:
tensor_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
print(tensor_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [38]:
tensor_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
casted_tensor_d = tf.cast(tensor_d, dtype=tf.int32)
print(tensor_d)
print(casted_tensor_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [39]:
tensor_d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
casted_tensor_d = tf.cast(tensor_d, dtype=tf.bool)
print(tensor_d)
print(casted_tensor_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [41]:
# checking for bool
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [42]:
# checking for tensor strings
tensor_s = tf.constant(['hello world'])
print(tensor_s)

tf.Tensor([b'hello world'], shape=(1,), dtype=string)


In [43]:
# checking for tensor strings
tensor_s = tf.constant(['hello world', 'hi'])
print(tensor_s)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


# Converting a numpy array into a tensor

In [45]:
import numpy as np


In [46]:
np_array = np.array([1, 2, 3])
print(np_array)

[1 2 3]


In [47]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [49]:
# construct identity matrix or batch of matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype = tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [50]:
# construct identity matrix or batch of matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype = tf.dtypes.float32,
    name=None
)
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)
